### ISSUE TITLE
Convert IA / MP DLLs to Lua

### ISSUE THREAD

**Issue by BlackDragonN001** [BlackDragonN001/FERemastered#1]
When patch is released:

-Convert IA / MP DLL's to Lua.
-Convert FE Enhancements/Features, or re-design them from the ground up. (3 way MPI, Portals, etc)
-Add enhancements/features if desired.
-Use modular design to easily share features between game modes.

**Comment by JJ173** [comment]
Closed - Mostly completed and in the works.
