### ISSUE TITLE
Animation for "ring" on Factory skips

### ISSUE THREAD

**Issue by Malifious** [BlackDragonN001/FERemastered#101]
Just as the title says.

While playing a match from the relay bunker, I noticed that the animation for the ring/archway on the EDF Factory skips when it makes a full rotation. The animation does not line up with itself and it looks noticeably choppy.

**Comment by JJ173** [comment]
Possibly a game issue. Can you check this without mods to verify? We haven't modified any of the ISDF animations for FE.

**Comment by BlackDragonN001** [comment]
Fixed.
