### ISSUE TITLE
Units are missing Cerberi Drainers

### ISSUE THREAD

**Issue by Malifious** [BlackDragonN001/FERemastered#105]
I've only observed two units in particular doing this, Scouts with rockets (Hidden Threats, Mission 9) and stock Turrets. Both shoot in a diagonal pattern across the drainer but do NOT hit it. They will deplete their magazine without hitting the target.
I am able to hit the target no problem but for some reason they're aiming in dead space rather that on the drainer itself (I think because the Cerberi extractors are offset compared to the other 3 races that are centered on the pool)

EDIT: I have no observed Msl. Scouts and tanks falling to the same behavior.

This makes it impossible to kill Cerberi Extractors without either doing it yourself or using a bomber.

**Comment by Malifious** [comment]
Upon further observation of the rocket scouts, they're shooting center and just above the scav.

**Comment by jack775544** [comment]
@BlackDragonN001 Wasn't this one fixed or did you only do the adjustments ISDF and Scion?

**Comment by JJ173** [comment]
This is a model issue and will be fixed when Jayden starts his work on the Cerberi remake. See: #4
