### ISSUE TITLE
Cerberi Missile Towers do not have a texture

### ISSUE THREAD

**Issue by Malifious** [BlackDragonN001/FERemastered#107]
Just as the title states.

These are the super gun towers like the one that Wyndt-Essex and her squad go to attack on Hidden Threats.

It comes up as a white, untextured tower rather than having the black/blue design.

**Comment by jack775544** [comment]
Generally we are not too worried about textures missing, things are going to get remodelled and textured anyway so a few odd props are sticking out aren't too important.

Closing this one though since it it is a duplicate of #78
