### ISSUE TITLE
Dread's are not using Slam Vortex that much

### ISSUE THREAD

**Issue by Malifious** [BlackDragonN001/FERemastered#109]
Traditionally, Dreads essentially weapon-linked by spamming rapido (or Cerberi Plasma, whatever their main attack is) and throwing in Slam Vortex every now and again. It caused a lot of problems for unit-based defenses and made fighting Dreads much more complicated.
They no longer use slam vortex outside of heavy opponents.

Now, it's as simple and fire/hide/fire/hide and you win.

**Comment by jack775544** [comment]
I linked the weapons together to emulate the old 1.2 behaviour but too be honest I do think it could be a little too powerful. Gonna leave this issue open for any followup work that needs to be done for this one.

**Comment by Malifious** [comment]
I'll take a look at the updated version and see how it feels. Traditionally, it felt to me like it made the Dread genuinely difficult to kill. Nowadays, they're really quite easy.

Will let you know how the tuning feels.

**Comment by JJ173** [comment]
Closing as the issue has gone stale and has also been addressed with 1.2 behavior.
