### ISSUE TITLE
Mortar Bikes floating around the map

### ISSUE THREAD

**Issue by Malifious** [BlackDragonN001/FERemastered#111]
Not sure what to make of this one. It's like the mortar bikes are drifting off from where they were told to stay and winding up 6-700m away, in random directions.

**Comment by jack775544** [comment]
Where do you see this happening. Can you replicate this one in stock?

We don't have that much control over the core AI for the units so we might be unable to fix it.

**Comment by Malifious** [comment]
I haven't seen it happen in stock ever and the only time it happened to me was on Hidden Threats.
No idea why, haven't seen the behavior anywhere else both on the campaign and IA.

Sure thing. And it could have been a one-off issue. I'll see if I can at least replicate it on Hidden Threats.

**Comment by JJ173** [comment]
Closing this as the issue has gone stale, no reproduction steps to view.
