### ISSUE TITLE
Attempting to start Mercury Rising throws 'Invalid Save File Detected' Error

### ISSUE THREAD

**Issue by VirtualDisk** [BlackDragonN001/FERemastered#117]
See title. Clean install of BZCC and FE. Used powershell script to install. 

![battlezone2 2020-06-03 14-31-51-647](https://user-images.githubusercontent.com/15205414/83650239-1e410600-a586-11ea-8153-451438b7091a.jpg)

Please let me know if there are any other details that I can provide that can help here.

**Comment by jack775544** [comment]
It would be a great help if you could upload the contents of your battlezone log file for when this error happened. The log should be located at `C:\Users\MyUser\Documents\My Games\Battlezone Combat Commander`

**Comment by VirtualDisk** [comment]
[Battlezone 2020-06-03 14.07.52.6953.log](https://github.com/BlackDragonN001/FERemastered/files/4726684/Battlezone.2020-06-03.14.07.52.6953.log)
[Battlezone 2020-06-03 14.29.15.1359.log](https://github.com/BlackDragonN001/FERemastered/files/4726685/Battlezone.2020-06-03.14.29.15.1359.log)

sure! see above.

**Comment by jack775544** [comment]
I can't reproduce this one on my system. I can see the error in your log file is 
```
DIAG|        loadsavegame:508  |14:14:02|369942 |Started LoadGame Type File
ERR |        loadsavegame:542  |14:14:02|369942 |SaveVersion too old. CANNOT LOAD PROPERLY!
DIAG|        loadsavegame:513  |14:14:02|369942 |Finished LoadGame Type File
ERR |         inithandler:787  |14:14:02|369942 |Unable to load mercedf1.bzn
DIAG|         inithandler:414  |14:14:02|369942 |Switching to CLEANUP, error during load seen
```
But I can't reproduce this one for the life of me. Going to have to look into this one further.

**Comment by jack775544** [comment]
Issue was to do with LF line endings in bzn files. Changing these to CRLF fixed the issue.
