### ISSUE TITLE
Mission: "The Other Side": The Pilot Weapon Is Scion Gun. It Should Be Human.

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#122]
The Pilot Weapon Is Scion Gun. It Should Be Human.

**Comment by bornlibra23** [comment]
![bz2_00001](https://user-images.githubusercontent.com/1274358/115738544-c502e080-a3aa-11eb-8fb4-7c68a18bd4d0.png)

**Comment by bornlibra23** [comment]
Fix: Edit fc01.bzn & Change curPilot = error To curPilot = isuser

**Comment by BlackDragonN001** [comment]
Fixed
