### ISSUE TITLE
Mission: "A New Alliance": The Xyr Guards Are Deployed Crooked By Default When Starting The Game

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#124]
The Xyr Guards Are Deployed Crooked By Default When Starting The Game. But Set Themselves Alright When Redeployed.
![bz2_00004](https://user-images.githubusercontent.com/1274358/115965190-8b1a1180-a545-11eb-922d-8defbccabd8b.png)
![bz2_00005](https://user-images.githubusercontent.com/1274358/115965191-8ce3d500-a545-11eb-9c97-52c5a4102bd8.png)

**Comment by BlackDragonN001** [comment]
Hmm, Likely a side effect caused by some different pivot in the original model vs the new model. Keep an eye out for things like this, especially with buildings, as things get remastered. (Props, Cerberi, etc)

**Comment by BlackDragonN001** [comment]
This should be resolved, yes?

**Comment by GraveyBoi** [comment]
This is resolved
