### ISSUE TITLE
Mission: "A New Alliance": The Build Dependencies Are Incorrect.

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#125]
Multiple Xyr Towers Are Allowed To Be Built.
Booster Pack Can't Be Built As Illustrated In The Image.
![bz2_00006](https://user-images.githubusercontent.com/1274358/115965291-14314880-a546-11eb-8552-9f4a522ac0f4.png)

**Comment by BlackDragonN001** [comment]
Fixed
