### ISSUE TITLE
Mission: Rebuilding The Ark (FC03): Some Objects Are Hovering In The Air

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#127]
Some objects are hovering in the air right below the initial plateau.
![bz2_00002](https://user-images.githubusercontent.com/1274358/116546549-5de7ad80-a90f-11eb-8151-7f94662ecde0.png)

**Comment by GraveyBoi** [comment]
These were done in the original for some reason. probably just need to be removed @BlackDragonN001

**Comment by BlackDragonN001** [comment]
Those are hovering spot lights.... at least they're supposed to be. They were used in some of the stock BZ2 missions irrc.

**Comment by GraveyBoi** [comment]
maybe I'm losing it but i don't remember those in stock, and those seem out of place for core as well

**Comment by BlackDragonN001** [comment]
We'll make some scion ones then sometime? but they do emit light, even if the cone angle is far less visible in bzcc compared to BZ2.
