### ISSUE TITLE
Mission: Rebuilding The Ark (FC03): Healing Ray Seems To Originate From Thin Air

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#128]
The healing ray doesnt originate from a single point on the healer model but it seems to start from the area above the model.
![bz2_00003](https://user-images.githubusercontent.com/1274358/116546725-96878700-a90f-11eb-9a03-06401a3042c9.png)

**Comment by GraveyBoi** [comment]
the front of the healing unit has a spinning dial / focus.
