### ISSUE TITLE
Mission: Rebuilding The Ark (FC03): Healing Ray Seems To Penetrate The Ground

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#129]
![bz2_00004](https://user-images.githubusercontent.com/1274358/116546790-ab641a80-a90f-11eb-8431-5b5df37a058e.png)

**Comment by GraveyBoi** [comment]
@BlackDragonN001 is this even fixable?

**Comment by BlackDragonN001** [comment]
That's a game engine thing and not something we can fix.
