### ISSUE TITLE
Mission: Rebuilding The Ark (FC03): The Dower Should Be Turned 180 Degrees

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#131]
This will allow the units to get on the pad quickly. Currently they go all around it.
![bz2_00006](https://user-images.githubusercontent.com/1274358/116547256-4957e500-a910-11eb-92f7-7115f5aa30c7.png)

**Comment by GraveyBoi** [comment]
@bornlibra23 this is intended so that units can use the dower front as a shield while healing
