### ISSUE TITLE
Mission: Biometal Meltdown (FC04): The Message Informing About Matriarch Repair Is Garbled

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#132]
It contains %i
![bz2_00007](https://user-images.githubusercontent.com/1274358/116547568-b3708a00-a910-11eb-9131-e12acd1ac6c8.png)

**Comment by BlackDragonN001** [comment]
Ah. Ok, I tweaked the code to load and implant the correct contents. I'm not sure if it should be using %i or %d., though.
