### ISSUE TITLE
Mission: Biometal Meltdown (FC04): The Created Smitcar Has No Pilot

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#133]
![bz2_00008](https://user-images.githubusercontent.com/1274358/116547746-ec106380-a910-11eb-9e92-61f093e01be3.png)

**Comment by GraveyBoi** [comment]
This is intended I believe? @BlackDragonN001 I always remembered it being empty? should we make it more clear to the player that its "empty scimitar"
