### ISSUE TITLE
Mission: Biometal Meltdown (FC04): Destroying This Resourcer Takes A Lot Of Time & Ammo Of The Ship 

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#134]
No other ship is available to kill it.
![bz2_00009](https://user-images.githubusercontent.com/1274358/116547951-2da10e80-a911-11eb-8104-eb9f0adcd917.png)

**Comment by JJ173** [comment]
Issue closed - this is just a case of Particle Gun vs Hadean Resourcer. I did take me a little while to kill it, but I was able to do so before the main attack waves began from the Royal Hadeans: 
![image](https://user-images.githubusercontent.com/94978675/188325466-1ebbf16c-2e6b-419e-a095-a695885d6098.png)
