### ISSUE TITLE
Mission: 3 Way Wild Wood: LUA GiveWeapon Issue

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#137]
![bz2_00003](https://user-images.githubusercontent.com/1274358/117283611-947b7600-ae83-11eb-94b6-86c8fe057a95.png)
![bz2_00004](https://user-images.githubusercontent.com/1274358/117283620-96ddd000-ae83-11eb-9ad4-6720497610df.png)

**Comment by BlackDragonN001** [comment]
Fixed.
