### ISSUE TITLE
Mouse Wheel Doesn't Work In Any Popup Window

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#14]
It doesnt work in debriefing, end of mission etc

**Comment by jack775544** [comment]
This one is a base game issue. The scroll wheel should work if you hover the scrollbar but it is outside the scope or ability for a mod to fix unless GBD has some magic fix that he knows of.

**Comment by BlackDragonN001** [comment]
Yea, this is something BZCC changed.
