### ISSUE TITLE
Mission: Biometal Meltdown (FC04): Jammer Destruction By Player Should Execute The Success Condition

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#142]
If the jammer is destroyed by the player instead of the SciWizard the success condition should trigger.

**Comment by bornlibra23** [comment]
Repo Steps:
Run ahead of the SciWizard & destroy the jammer even before he arrives. The game would progress with the SciWizard as if the jammer was still there. He would destroy the already destroyed jammer & the game would follow course.

**Comment by GraveyBoi** [comment]
@BlackDragonN001 can you close this?

**Comment by GraveyBoi** [comment]
nvm found it

**Comment by bornlibra23** [comment]
Thank you.
