### ISSUE TITLE
[BUG] EDF Mission 10 (edf09) - Escape Path: Recycler doesn't break down

### ISSUE THREAD

**Issue by NickDoggerMc** [BlackDragonN001/FERemastered#143]
On first play through, got to the portal but mission didn't progress. Turns out, recycler didn't break down as it was supposed to so didn't progress routine states. I checked using prints to print distance and shift+f9 view, turns out recycler doesn't get within 25m of breakdown waypoint to trigger it (Gets within 27m).

FIX: Increase distance recycler has to be within to trigger on line 213 of edf09.lua (I tried 35m which worked). Alternatively, could adjust position of breakdown waypoint

**Comment by BlackDragonN001** [comment]
Adjusted distance, based on recommendation.
