### ISSUE TITLE
[BUG] EDF Mission 1 (mercedf1) - Mercury Rising: Gun tower at power doesn't aim correctly

### ISSUE THREAD

**Issue by NickDoggerMc** [BlackDragonN001/FERemastered#144]
The GT at power supplies doesn’t actually look directly at players ship, turret/cannon rotation seems to be offset slightly so never actually shoots, though at some angles it will be looking at player correctly and fire. Must be an odd tracking issue.

**Comment by BlackDragonN001** [comment]
Should be fixed, the gun tower had a saved Velocity in the BZN. So it thought it was moving and was trying to compensate for that???
