### ISSUE TITLE
[BUG] EDF Mission 3 (edf02) - A Surprise: Recycler issue in F1 group with other units

### ISSUE THREAD

**Issue by NickDoggerMc** [BlackDragonN001/FERemastered#145]
Minor bug:
If you have units in F1 group when recycler is given to your command and put into f1 slot, can’t use ~ key to access the other units in the group i.e. acts as if only recycler is in that slot, and can’t deploy recycler without selecting it by pointing at and pressing space, deploy command not visable with group selection.

**Comment by BlackDragonN001** [comment]
Changed to SetBestGroup().
