### ISSUE TITLE
[BUG] EDF Mission 4 (edf03) - Power Struggle: Multiple missing labels in BuildAndLabelObject function calls

### ISSUE THREAD

**Issue by NickDoggerMc** [BlackDragonN001/FERemastered#146]
Came across a bug where Recycler wouldn't deploy at base site as Lua Script Update error: [string “_DLLUtils.lua”]:216: bad argument #1 To ‘GetHandle’ (string expected, got nil) was being thrown, was just a call to BuildObjectAndLabel that didn't have the 4th argument "Label", BuildObjectAndLabel("raptor01", 9, "dino1") so just made it BuildObjectAndLabel("raptor01", 9, "dino1", "Dino 1"). There were a few calls like this without the label so did similar to them

Fixed 2 more bugs involving similar errors with the BuildObjectAndLabel:
- One was engineer pilot being given same label as engineer transport, so pilot never spawned and when pilot was removed, transport was actually removed instead, failing the mission
- Labelled the beam that destroys the base as it was missing one and causing errors

I initially thought the Engineer pilot issue was due to being spawned at the position of the transport, so potentially spawning inside it or something weird. Luckily it wasn't, but maybe something to watch out for. Maybe slightly offset his spawn position from the transport to make sure

Fixed script attached:
[edf03.zip](https://github.com/BlackDragonN001/FERemastered/files/6950954/edf03.zip)

**Comment by BlackDragonN001** [comment]
Fixed.
