### ISSUE TITLE
EDF Mission 13 (edf14) - Cloak of Deception: Mission description cut-off

### ISSUE THREAD

**Issue by NickDoggerMc** [BlackDragonN001/FERemastered#147]
Minor issue:
Mission description is cut-off at “betwenn” due to description being longer than 10 lines, can fix by moving text to upper lines (not past 10 lines total), also minor spelling error. Suggested edit below.

Edit:
We have emerged on Facility's surface.
While Eisenstein searches for data on
the Hadeans' plans, your force will
concentrate on sabotage and subterfuge.

Your primary mission is to attack an
Imperial installation while in Cerberi
disguise, in order foment mistrust and
suspicion between the Imperial Hadean
forces and their Cerberi minions.

**Comment by BlackDragonN001** [comment]
That's actually the listbox size being way too small. Hmm. Whoops. Fixed.

**Comment by NickDoggerMc** [comment]
Ah, fair enough. Was wondering if that could be changed.
