### ISSUE TITLE
[BUG] EDF Mission 14 (edf15) - Betrayed: Debrief for Hadean choice is blank

### ISSUE THREAD

**Issue by NickDoggerMc** [BlackDragonN001/FERemastered#148]
The debrief for choosing Hadean doesn’t display any text, is blank (Could be after loading mission from save file but EDF debrief works fine regardless). Txt file name is correct, thought it might be something to do with the ChangeSide() function call but removing it didn't seem to make a difference.

**Comment by BlackDragonN001** [comment]
fixed.
