### ISSUE TITLE
Single Mission Screen: Mission Description has white background

### ISSUE THREAD

**Issue by NickDoggerMc** [BlackDragonN001/FERemastered#149]
ColorGroup is set to white atm

Should also add, text can now be highlighted and selected in the description which I'm assuming isn't intended behaviour? Probably new bzshell_single.cfg config just needs tweaking.

![image](https://user-images.githubusercontent.com/38968235/128868357-9fec997a-0135-4751-b6ce-7418c2047ce7.png)

**Comment by BlackDragonN001** [comment]
oops, fixed.
