### ISSUE TITLE
Craft can move right through the initial dropship in the first mission.

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#15]
It can move from inside outward or outside inward.

**Comment by GraveyBoi** [comment]
The problem lies with the model being used not having collisions. The model itself might need to be update as well as its an ISDF dropship not an EDF one. Unless there was some lore intent here?

**Comment by GraveyBoi** [comment]
Also the MITS mine that holds the player down needs to be extended 1 second or so that the player cannot move until the doors open

**Comment by JJ173** [comment]
The model is down to the fact that we're using the orange version of a Condor ship. We should probably consider updating it to a normal one.
