### ISSUE TITLE
Firing back: recycler path glitch

### ISSUE THREAD

**Issue by GokuSonic** [BlackDragonN001/FERemastered#151]
Recycler is stuck and wont move. Even after I push it out towards nav delta it tries to go back to base then stops
This is when you have to help the recycler to nav delta.
[https://imgur.com/a/aksjEZQ](url)  stuck in base
[https://imgur.com/a/kOyd7TV](url) goes back to base and sits there

**Comment by JJ173** [comment]
Duplicate of #30
