### ISSUE TITLE
Kruls are "Stuck" in Crucible

### ISSUE THREAD

**Issue by BZdJunge** [BlackDragonN001/FERemastered#153]
When a Krul is builded, instead of dropping out it will turn around and driving against the building. In this instance you can attack them without any resistance. Only in rare cases they can somehow leave the Crucible.

This issue happens in every mission, where the Crucible exists, and also in instant missions (AI and player).

![20220312214645_1](https://user-images.githubusercontent.com/107756798/174438373-bd7a992a-1fbb-43b7-88a4-67be204492e7.jpg)

**Comment by GraveyBoi** [comment]
lol, looks like this is missing the tunnels I added for vsr? @BlackDragonN001

**Comment by JJ173** [comment]
Fixed.
