### ISSUE TITLE
Lull in initial mission after the major essex reach back

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#17]
On medium difficulty there is a lull in the mission when essex reaches back to the transports. It makes the player think as if there is an error.

**Comment by JJ173** [comment]
What is "Lull"?

**Comment by jack775544** [comment]
There is a bit of downtime to repair everything before the next drone attack comes

**Comment by JJ173** [comment]
Difficulty isn't taken in to account here, this will happen in the mission regardless. How long is the wait time?

**Comment by Feared1** [comment]
This happens on multiple missions, but it is definitely noticeable in mission 1.

Also, mission 8: After being told to return to base, I finished off the first wave of attacks, and then there was a long wait - no more attacking

**Comment by GraveyBoi** [comment]
Resolved with recent updates. Mission plays at a much better pace for Mission 1.
