### ISSUE TITLE
After essex reaches back in mission 1 her target indicator disappears but she is still a key unit

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#18]
This makes it difficult to protect her

**Comment by jack775544** [comment]
On one hand I agree, on the otherhand your transport and Hardin are also required to stay alive for the mission so it could be confusing if one of those die as well. We could highlight all of them but then it would just be very clustered

**Comment by JJ173** [comment]
I'm with @jack775544 here. The only objective indicator should be on the unit that's the current focus.

**Comment by GraveyBoi** [comment]
I think this is closeable, however, I think when Essex complains about getting repairs on her path back she should be highlighted.

**Comment by JJ173** [comment]
Agreed with the last point. Added an enhancement label. I will set myself to get this fixed.
