### ISSUE TITLE
EDF03: Cerberis won't patrol

### ISSUE THREAD

**Issue by BZdJunge** [BlackDragonN001/FERemastered#192]
In the Ruined City the Cerberis have no way-points for patroling the area. They just stand around.
![20221105205842_1](https://user-images.githubusercontent.com/107756798/200138836-0202fad2-cab0-4fb3-9779-e38c87b65538.jpg)

**Comment by BlackDragonN001** [comment]
investigated this some....so far this has stumped me :-/ might be a game engine bug? 

TODO: investigate other places where a group of units are set to Patrol (using GoToTaskHasLeader = true)

**Comment by BlackDragonN001** [comment]
oops, that commit is meant for issue #191.

**Comment by BZdJunge** [comment]
You can take a look to EDF13. In this mission the Hadeans are patroling just fine

**Comment by BlackDragonN001** [comment]
Hm, thanks for pointing that out. The only diff i saw, was priority of the Patrol command. 

EDF03 had patrol with priority 1. 
EDF13 had patrol with priority 0.

Setting priority to 0 seems to have fixed it. :-/ darn game bugs...
