### ISSUE TITLE
Separation of Assets

### ISSUE THREAD

**Issue by BlackDragonN001** [BlackDragonN001/FERemastered#2]
Once things are ready, the assets should be split into the following Asset Packages:

FE UI << All non mission specific UI / BG art/ CFGs.
FE Campaign << All SP maps, and SP specific props/assets/briefings/VOs/etc.
FE Hadean << All Hadean race assets, including hadean specific weapons.
FE Cerberi << All Cerberi race assets.
FE ISDF << All ISDF race sssets.
FE Scion << All Scion race assets.
FE Map Assets  << All IA and MP map BZNs/Assets. (DM only weapons, units, etc)
FE Map Pack << All MP MapTERRAIN only map specific assets: Textures, pools, TER/SKY/WAT/TRN only. No .BZN or other ODFs, those will be in the FE Maps package.

**Comment by Nielk1** [comment]
It might be safe to put the FE UI and Campaign into the config mod with the core.  As BZNs and INIs aren't really reasonably able to be dropped in another mod they might also be able to be part of the config mod, though on request they could be broken out if someone wants to do an FE variant and wants better efficiency.

I'd add FE Worlds to the list which would contain ODFs, Textures, and Models specific to worlds and biomes.  FE Map Pack would depend on this, supplying the TERs and such of the actual maps.

**Comment by JJ173** [comment]
I think GBD has handled most of this now. Closed as part of clean-up.
