### ISSUE TITLE
Mission 1 - Cerberi unit being sent to space

### ISSUE THREAD

**Issue by jack775544** [BlackDragonN001/FERemastered#21]
I do see the GBD comment in the lua stating 

> I don't like the idea of this poofing into nothingness. Do something else? either leave it till it's offmap, or zoof it up into space? actually, hold that thought...

But perhaps a call to TeleportOut would be better instead

**Comment by BlackDragonN001** [comment]
oo yea, i forgot, i did that as a joke for Gravey. I should undo that XD.

**Comment by GraveyBoi** [comment]
We'll we more or less need to do something with it so it doesn't just auto delete the unit if you catch it too early. Is there a reason it auto deletes there, but doesn't elsewhere?

**Comment by BlackDragonN001** [comment]
Fixed?
