### ISSUE TITLE
APC and Crashed Drop Ship on EDF01 are assigned team 1 instead of team 0

### ISSUE THREAD

**Issue by GraveyBoi** [BlackDragonN001/FERemastered#22]
See title and FE-Testing https://discordapp.com/channels/271066904284758027/460900852757037057/693192855879155753

**Comment by jack775544** [comment]
![map](https://user-images.githubusercontent.com/8287765/77806681-15890b00-70d1-11ea-8d0f-d539d384a383.png)
![dropship](https://user-images.githubusercontent.com/8287765/77806687-17eb6500-70d1-11ea-9092-9d00e00e4548.png)

^ Images posted in discord

**Comment by GraveyBoi** [comment]
I've updated this in my map edits branch. Problem is fixed!
