### ISSUE TITLE
Mission 4 - Power Struggle: If The Pack Explosive Isnt used The Game Doesn't allow Story Progression

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#24]
If I dont use the pack explosive to blow up the rocks then the game doesnt trigger next scenario on my arrival in the ruins.

**Comment by bornlibra23** [comment]
In such a case I suggest that the game play should be allowed to continue & the rocks be required to be blown up when the engineers need to be escorted.

**Comment by JJ173** [comment]
How did you manage to get to the ruins without completing the objective to destroy the rocks? IIRC this shouldn't be possible as the only other logical entrance is beyond the enemy Mega Guns.

**Comment by bornlibra23** [comment]
I simply moved through the rocks. I could also have shimmied up the mountain sides.

**Comment by bornlibra23** [comment]
If you want I can make a video if you let me know how.

**Comment by GraveyBoi** [comment]
if you want download OBS and set it up to record. If not I can do a proof run of this right now since I've noticed this as well. Its not fully blocked off in the area the pilot is intended to walk which allows units to pass through.

**Comment by bornlibra23** [comment]
Please check it on highest graphical configurations. In BZCC Scion Mission 1 the problem happened with low graphics & not with high graphics.

**Comment by bornlibra23** [comment]
Can we allow the Bomber to destroy this as well? It will make it an additional option.
