### ISSUE TITLE
Mission 4 - Power Struggle: Continuous Audio Recount Of "Unit Lost" Is Quite Irritating

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#26]
When the mega gun vaporizes the base the game plays "Unit Lost" for every unit. This is quite irritating to hear & distracts from the game play.

**Comment by JJ173** [comment]
Not really sure this is an issue given that it's a default game mechanic and your entire base is wiped out at the same point. The only way we could probably avoid this is by changing the team of the players base to team 0 but I don't think this is an ideal solution.

**Comment by GraveyBoi** [comment]
I would agree with JJ here. This is something we just have to deal with given the dated engine, unless we were to somehow do team 0 by base location to include all units and buildings that would be hit by the blast. But even then, you wouldn't get the message, which would turn into a new issue of player not being notified of lost units and base if they skip the cutscene.
