### ISSUE TITLE
Mission 4 - Power Struggle: Story needs to be changed to induce the player to have constructor separate from the base

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#27]
I think that the game stody needs to be changed to that the player will have a constructor away from the base so that some buildings etc can be built. Otherwise if the player has concentrated his forces then he will have no way of destroying the base.

**Comment by bornlibra23** [comment]
In such a case the factory can be designated as the basic base building.

**Comment by JJ173** [comment]
Closing this - This mission has always been that way. The player is expected to have units scattered around outside of their base perimeter in order to complete the final objective. Not doing that is not the fault of the mission, it just employs additional strategy.

**Comment by bornlibra23** [comment]
Okay but I would need assault tanks for this & there is no reason to build them beforehand. Of course I am assuming that I will finish it in a single playthrough.
