### ISSUE TITLE
Mission 5 - Firing Back: Recycler doesnt go to the nav point when instructed

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#29]
When commanded to go to the nav point the recycler doesnt go there instead it gets stuck at the inner cusp of the mountain as it it expects to go to the nav directly in a straight line from its original position. Seems to be a pathing issue. It does appear to follow when instructed. Also somehow it now has seemingly managed to destroy itself without being attacked.

**Comment by bornlibra23** [comment]
Tested it again. The recycler just killed itself while in transit to the deploy point at the nav point.

**Comment by GraveyBoi** [comment]
I've pushed a terrain patch on my branch that should fix this. Pending GBD's approval.

**Comment by JJ173** [comment]
@GraveyBoi I don't see your Pull Request, was this approved and merged?

**Comment by GraveyBoi** [comment]
has not yet been approved, still waiting

**Comment by JJ173** [comment]
I don't see a PR active for the master branch @GraveyBoi: 
![image](https://user-images.githubusercontent.com/17053495/78831750-116ac080-79e2-11ea-9e5d-07d4f3015159.png)

You 100% certain you made it for this one?
