### ISSUE TITLE
Mission 6 - Sheep's Clothing: Recycler needs to be fetched

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#32]
Perhaps it should be clear in the information box the the recycler needs to be fetched & not just escorted.

**Comment by GraveyBoi** [comment]
Where does this apply and at what point in the mission?

**Comment by bornlibra23** [comment]
Sorry I should have been clear. After the hadean units have been picked up
at the repair base the player has to go to the recycler to trigger it to
start moving.

**Comment by JJ173** [comment]
Is there not an audio queue for this?

**Comment by bornlibra23** [comment]
No

**Comment by JJ173** [comment]
I wouldn't really call this an issue. I would suggest it's more of an enhancement. Given that the entire mission is based around the player defending the Recycler anyway, it seems canon for them to return to it and some stage after getting the Hadean Vehicles from the repair base.

**Comment by bornlibra23** [comment]
Okay. But if we can have hold & move commands on the defined path for the recycler then it would be great.

**Comment by GraveyBoi** [comment]
I don't actually remember ever having to return to it during my playthrough. I remember it coming down automatically after I moved toward the exit portal. My service trucks still followed it down the hill. I'll play through and test this really quick.

**Comment by JJ173** [comment]
Addressed.
