### ISSUE TITLE
Heavy Chain is available on missions other than edf07

### ISSUE THREAD

**Issue by GraveyBoi** [BlackDragonN001/FERemastered#33]
Why is this in the tech tree for other missions than edf07? edf04 is the first that comes to mind.

**Comment by JJ173** [comment]
I'm going to make a point of ensuring that the Heavy Chain is available throughout the campaign here. We need to make sure that the tech tree matches in most cases especially for the later missions. This is likely down to funky ODF inheritence or lack thereof.

**Comment by JJ173** [comment]
Cleaned up as part of the above Pull Request.
