### ISSUE TITLE
Mission 10 - Escape Path: Error at mission start

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#34]
According to http://jack775544.github.io/forgotten_enemies_walkthrough/10%20%20Escape%20Path.htm I should have a recycler at mission start. However I dont have one & there is no mission briefing in the box & no voice over. This is the error displayed:
**Lua script load error: [striing "edf09.lua"]:6: ')' expected near ';'**

**Comment by jack775544** [comment]
Fixed
