### ISSUE TITLE
Mission 9 - Hidden Threats: Cerebri Drainer Isnt Targeted At Start

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#35]
Neither Essex's units not towers I set up targeted the initial drainer. The shots seemed to go over it. A very few did hit. I had my tower 5 slots right & 1 slot up from the drainer as viewed in satellite mode.

**Comment by jack775544** [comment]
Yeah we have noticed this for some structures and were talking about it a couple of days ago, the isdf and scion extractors also have the problem but to a lesser degree.

The solution will be to move the targeting point to where the drainers model actually is.

**Comment by GraveyBoi** [comment]
This will likely get fixed when Jayden gets around to working on updated models. Currently the hardpoint is in the center of the model which is incorrect.

**Comment by JJ173** [comment]
I wouldn't really call this an issue as of yet given that Jayden has still got to remake the entire Cerberi Arsenal. 

It's something worth noting when he does it for sure, but at this point it's too early to worry about this.
