### ISSUE TITLE
SP Objective Box is too small

### ISSUE THREAD

**Issue by JJ173** [BlackDragonN001/FERemastered#36]
In some missions I have noticed that the objective text is too long for the standard sizes SP box to display correctly. I would propose that we modify the UI slightly and make it taller to ensure that all mission objectives are displayed clearly.

**Comment by bornlibra23** [comment]
Please make the box automatically resize able given the length of the message & have it aligned a the middle across multiple messages.

**Comment by GraveyBoi** [comment]
I dont have any experience with config items, but would that be possible using character length sizing? so if > 60-characters do size x if else > ,....., Also would that cause inconsistency with capitalized lettering and line breaks?

**Comment by JJ173** [comment]
Unfortunately you can do the bare minimum with config files. You can't do any conditional checks to increase sizing. We'd have to decide on an ideal upscale and stick with that throughout.

**Comment by BlackDragonN001** [comment]
Increased height by 30px.
