### ISSUE TITLE
Mission 09 - Escape Path: The Recycler Vanishes Near The Portal & The Player Loses

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#38]
As soon as the recycler reaches the portal it disappears in a blue sphere which dissipates afterwards & the player loses automatically without any enemy unit present.

**Comment by bornlibra23** [comment]
I tested this again & it still happens. I cant seem to go through the portal.

**Comment by bornlibra23** [comment]
I see
_page = 0
entered = 1
warnrestartchanges = 1_
before losing.
And 
_entered = 1
warnrestartchanges = 1_
right after

**Comment by GraveyBoi** [comment]
Can confirm this is true.

**Comment by bornlibra23** [comment]
I just game.cheat bzwinner 'ed it out.

**Comment by jack775544** [comment]
If you could upload a save game for this one that would be amazing. I'll take a look at this tonight.

**Comment by JJ173** [comment]
You can replay this to replicate it @jack775544 - We just need to improve our handling around the portal. Please note though that the player should never go through the portal as the Recycler is teleported to a boundary of the map that would just bug the player out if they even attempted to go that far. 

I think we're just missing a variable assignment when the Recycler is teleported out.

**Comment by GraveyBoi** [comment]
It's likely a variable, I never touched the portal in my playthrough. I'll get a save shortly.

**Comment by GraveyBoi** [comment]
lol file unsupported rip. I'll pin it in testing Jack.

**Comment by bornlibra23** [comment]
[5.sav.log](https://github.com/BlackDragonN001/FERemastered/files/4454292/5.sav.log)
Please rename the file

**Comment by jack775544** [comment]
Fixed, the mission now succeeds correctly for me
