### ISSUE TITLE
Mission 09 - Escape Path: When Antibodies Spawn They Seem To Be Stacked Onto Each Other

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#40]
Sometimes when antibodies spawn there are stacked antibodies usually above the spawn point. This stack never reduces.

**Comment by GraveyBoi** [comment]
Hey libra, could you add some screenshots to this so we can visibly see the description? Thanks! I'll take a look at this when I get the chance. How did you trigger the antibodies to spawn and stack? They shouldnt spawn unless an enemy unit passes by.

**Comment by GraveyBoi** [comment]
![20200408102328_1](https://user-images.githubusercontent.com/53205387/78796420-447e6700-7984-11ea-8285-cd59ddf40a6f.jpg)

**Comment by GraveyBoi** [comment]
I assume this is what you're talking about

**Comment by bornlibra23** [comment]
Yes but somehow I cant see the monsters in my game. One of which looks like its puking them out of its mouth. How did you take this screenshot? I dont know how.

**Comment by bornlibra23** [comment]
I play on low graphics. Maybe thats why I can't see the monster. The antibodies must be inside it. That would make sense but still it shouldn't be visible.

**Comment by GraveyBoi** [comment]
f12 on steam or use a different capture service like Microsoft game bar.

**Comment by bornlibra23** [comment]
Thanks. I will use Ctrl+G.

**Comment by JJ173** [comment]
Possibly down to the weapon that creates these anti-body objects. Might need to increase their distance of which they track objects.

**Comment by JJ173** [comment]
Going to merge with issue #69 as the same fix will likely resolve both of these issues.
