### ISSUE TITLE
EDF09 "We've Broken a Tread" 

### ISSUE THREAD

**Issue by GraveyBoi** [BlackDragonN001/FERemastered#41]
The placement of the recycler is inconsistent here. I've had it break its tread in the volcano (which sucks to try to play through after because my trucks get wrecked during the movie play through and the rec is barely alive) and sometimes outside of the volcano. The occurrence seems to have some inconsistency. Is there any way we can make sure it happens at a proper location (where is it intended to break?)

**Comment by bornlibra23** [comment]
Or we can have it by damage.

**Comment by GraveyBoi** [comment]
I don't think by damage would work, a player could circumvent it entirely.

**Comment by JJ173** [comment]
I believe this is down to a timer. Possibly a bug with it. I think I've had this once where I undeployed the Recycler quite late and had the "Tread Break" event occur like 10 seconds after I left my base perimeter. 

I will have a look at the pathing logic of this and possibly turn this into a distance check event.

**Comment by jack775544** [comment]
Yes it is on a timer. I just checked the script and it happens 200 seconds after the rec undeployed.

**Comment by JJ173** [comment]
I thought so. I think we'd be better off having a dedicated path for this that the Recycler goes to for the first part of it's journey. Once the tread break event has completed, we can then tell it to move to the portal. 

We need to decide where the best place for this is. Does anyone want to suggest an area? Maybe the volcano could be good for difficulty, especially if it shoots projectiles.

**Comment by GraveyBoi** [comment]
so routinely it breaks either just before  the volcanoes fire. It should be just before imo because if you don't have 3 service trucks its dead by the time it fixes itself.

**Comment by GraveyBoi** [comment]
Playthrough just now, made it the whole way past the volcano.....

**Comment by bornlibra23** [comment]
> I don't think by damage would work, a player could circumvent it entirely.
That still would be okay. It really isn't needed for the story progression apart for other events possibly triggered by it. And it would be a gift to players who keep the recycler from getting hit.
