### ISSUE TITLE
Mission 12 - Heart of Darkness: No Audio Notification For South West Tower If Accessed First

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#42]
If Einstein is taken to the south west tower first instead of the east he gives the Tartarus data but never finishes. I have waited through two attack waves.

**Comment by bornlibra23** [comment]
Update:
It seems that the support crew unit removes itself from F4 when it reaches the said tower. The it gives me the tartarus data & then comes back to F4. I assume that the work is done & will move to the other tower.

**Comment by bornlibra23** [comment]
Yes it does trigger the elevator voice over. So it seems that there just isnt an audio notification for the south west tower.

**Comment by bornlibra23** [comment]
On another note the pathing in this mission is pretty troublesome. I have separately had recycler & the tug go into the lava with no enemy units around & no one firing on them. The recycler went in near the ammo pod on the opposite side.

**Comment by bornlibra23** [comment]
The voice overs seem to be tied into the actual tower rather than the sequence of access.

**Comment by jack775544** [comment]
I played through the mission and didn't have any problems, the voice lines seemed to all trigger correctly. Perhaps we could unhighlight the tech center after the tech support vehicle has visited it to make it more obvious that you can continue on.

**Comment by bornlibra23** [comment]
> It seems that the support crew unit removes itself from F4 when it reaches the said tower. The it gives me the tartarus data & then comes back to F4. I assume that the work is done & will move to the other tower.
> I played through the mission and didn't have any problems, the voice lines seemed to all trigger correctly. Perhaps we could unhighlight the tech center after the tech support vehicle has visited it to make it more obvious that you can continue on.

Didnt this happen to you?

**Comment by JJ173** [comment]
Closing - tested and it seems to work if you take the Engineers to either tower first.
