### ISSUE TITLE
Mission 13 - Cloak of Deception: Mission Fails If I Try To Access The Jammer Next To The Base

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#43]
Mission Fails If I Try To Access The Jammer Next To The Base. Though I tried only after I was instructed to go to the scrap pool. I will check again earlier as well. It may have been a mistake. The message says that "you were only asked to destroy cerebri gun towers....."

**Comment by bornlibra23** [comment]
Please hold. Let me retry.

**Comment by JJ173** [comment]
I don't think this has any relation to accessing the jammers as you would a normal comm bunker? Are you sure some of yours units didn't stray off and attack some highlighted Defenders when they shouldn't?

**Comment by bornlibra23** [comment]
I did destroy two defenders & two battery trays myself but that was long before the mission loss.

**Comment by JJ173** [comment]
If you're not in a Cerberi unit, then this is why you lost. Odd that it took so long to tell you that though. It could be you destroyed them before the mission checks activate.

**Comment by bornlibra23** [comment]
No I was in my scout. Still it was long after I destroyed them.

**Comment by JJ173** [comment]
Okay that's a bug with the existance checks of those towers then. Ideally you shouldn't destroy those Defenders until instructed to do so with only Cerberi units. If you did it before the Jammers were constructed, it would have likely failed your mission after the Hadean Constructor finished it's part.

**Comment by bornlibra23** [comment]
Yes thats what happened. I guess it happened because I destroyed them with a scout rather than a cerebri unit. Or did it happen just because i destroyed them before being instructed to?

**Comment by GraveyBoi** [comment]
probably destroyed them before being instructed to
