### ISSUE TITLE
Mission 13 - Cloak Of Deception: Can't Win Even after obliterating everything off the map

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#44]
In Cloak Of Deception is the geothermal control station to be destroyed? If yes then my units do that but even after eliminating everything on the map I still don't win. If not then it shouldn't be a targetable building.

**Comment by JJ173** [comment]
@GraveyBoi didn't you say this happened for you?

@bornlibra23 Was there any log errors on this?

**Comment by GraveyBoi** [comment]
yes, this was a bug listed on mantis.

**Comment by bornlibra23** [comment]
Sorry I didnt take the logs. I guess I am still not proficient in capturing bugs. I will try again.

**Comment by JJ173** [comment]
Well can we make sure to get logs for this please. I cannot fix it without the proper context unfortunately.

**Comment by jack775544** [comment]
If you could get a save game with this happening that would be great. I haven't been able to replicate this bug myself which makes it really hard to track down.

**Comment by bornlibra23** [comment]
If I decide to go & destroy the geothermal power station myself then it works but if I send my units to destroy it then it doesnt.

**Comment by bornlibra23** [comment]
I will get you the log on my next play through.

**Comment by GraveyBoi** [comment]
Is the win condition check destroyed by player or destroyed by player team?

**Comment by bornlibra23** [comment]
The Geothermal Control Center isnt highlighted if my units stumble across it. I guess thats the problem but I am still testing.

**Comment by JJ173** [comment]
When did you stumble across it? Was that before you sniped the scouts, or killed the defenders?

**Comment by bornlibra23** [comment]
I just had my units destroy the GCC but no dice. Here is the log.
[Battlezone 2020-04-13 19.46.38.5109.log](https://github.com/BlackDragonN001/FERemastered/files/4469980/Battlezone.2020-04-13.19.46.38.5109.log)

**Comment by bornlibra23** [comment]
> When did you stumble across it? Was that before you sniped the scouts, or killed the defenders?

After I destroyed the defenders.

**Comment by JJ173** [comment]
Okay this isn't anything to do with syntax from the looks of that log. It's likely a logical error. IIRC the Geothermal should highlight once the defenders have died. I wonder if something is going wrong after that.

**Comment by bornlibra23** [comment]
Yes. Right now it only triggers only if the player himself drives to near the GCC. I havent tried destroying it with units once I do that. I will.

**Comment by JJ173** [comment]
I've tested this and it seems to be functioning as expected. Closing issue.
