### ISSUE TITLE
Mission 14 - Betrayed: If I Kill Schultz Beforehand The Games Doesn't Progress

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#46]
If I kill Schultz beforehand & his tank, however I cant destroy the constructor, then the cut scene just has the camera moving around the recycler without any voice over. Also the objectives don't change & even after reaching the tunnel nothing happens.
At least the game should fail if I kill Schultz.

**Comment by bornlibra23** [comment]
Also I suggest that the constructor be designated as an enemy unit & any units I may have created like turrets or gun towers should attack & kill him.

**Comment by bornlibra23** [comment]
The constructor should be destructible & have the game fail on their destruction.

**Comment by JJ173** [comment]
I disagree to both of the last 2 comments. The Constructor is key to the cutscene and should not be destroyed by player means. 

Also they seem to contradict a bit. Having the Constructor set to the enemy team but then failing the player for killing it? What would be the need?

The Schultz thing is interesting though. That will need further testing. It's likely because his pilot doesn't exist after killing the tank.

**Comment by bornlibra23** [comment]
Let me summarize & clarify:
All three Schultz, his tank & constructor should be destructible. Destruction of any of these should result in a mission failure.
Any unit created my the player before leaving the base should attack Schultz when he tries to destroy the jammer.

**Comment by JJ173** [comment]
No they shouldn't, it clashses with the appropriate voice audio then as well. 

As soon as Schultz gets in his Constructor, Colonel Stewart starts yelling at him to get out of it. They have some chatter while Schultz is destroying the Jammer. As soon as Schultz finishes, he bails and moves out. There's no way that Constructor would survive in that cutscene against 6 deployed turrets for example. It breaks the entire scenario to do so. 

It'd be silly for us to shoot Schultz destroying our only available Constructor in the process for then Stewart to say "Schultz took out the Jammer as well as our only Constructor". 

The only problem at the minute is that the script doesn't account for the fact that Schultz can be killed by players. The rest of the suggestions don't make sense.

**Comment by bornlibra23** [comment]
Okay. If you say so. Lets just have Schultz, his tank & the constructor indestructible. That would solve everything.

**Comment by JJ173** [comment]
Probably best for this scenario at the minute. Good job on finding the Schultz issue though.

**Comment by JJ173** [comment]
Fixed.
