### ISSUE TITLE
ODF: Race Configuration

### ISSUE THREAD

**Issue by BlackDragonN001** [BlackDragonN001/FERemastered#5]
Setting up Race specific ODF items, such as build sparkers, Nav beacons/dropoffs, etc. 1.3 added a lot of features to properly support individual Races. 1.2 lacked this so there might be some rude hacks or etc left around.

**Comment by JJ173** [comment]
I think this was cleaned up as part of our ODF clean. The Hadeans now seem to have their own sparkers and what not implemented. Is there anything else we need to consider here before closing?

**Comment by JJ173** [comment]
Seems to have been done so closed.
