### ISSUE TITLE
Mission 1: My pilot died during the final cutscene and I failed the mission

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#51]

**Comment by JJ173** [comment]
How was your pilot killed? 

Need some replication steps.

**Comment by GraveyBoi** [comment]
the AI still functions during the cutscene but the player cannot. Doesn't pause game time while it happens so if you're in a bad spot you die.

**Comment by JJ173** [comment]
This still doesn't answer my question. There's various AI that could contribute here, such as the Gun Towers or Drones. 

I'm also certain that your team gains control of 4 of the 6  Gun Towers guarding the base as well.

**Comment by jack775544** [comment]
Easy solution would just be to ally the drone team with yours when the cutscene starts.

**Comment by Feared1** [comment]
I don't know what killed me - I was in the middle of a cutscene.

Based on what was going on immediately before the cutscene, I would assume it was a drone. Basically, when the cutscene occurs, there should be NOTHING left on the map that is able to kill me. The cutscene ends the mission. Ally EVERYTHING to the player at that time to prevent this.

**Comment by jack775544** [comment]
Allied drones with player at the start of the cutscene.
