### ISSUE TITLE
Mission 3: Inconsistent portal exit

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#53]
When going through the portal, your units end up all over the east side of the map in various portals. Not sure if this is supposed to just be 1, but it seemed very odd to me.

**Comment by JJ173** [comment]
Possible cause of GBD's new Portal DLL that was introduced as apart of this remaster.

**Comment by GraveyBoi** [comment]
This is intended.

**Comment by GraveyBoi** [comment]
Fixed by GBD
