### ISSUE TITLE
Mission 4: End of mission dead end?

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#55]
I had hardly any forces left after my base was destroyed with no way to rebuild. I also received no reinforcements. Luckily I had built a Walker early on just for FUN and moved it away from my base so it survived the Megagun and I was able to finish the mission - this was not part of the instructions and purely coincidental.

Either send reinforcements or have some instruction to move out a small fleet of units before the Megagun destroys your base.

**Comment by JJ173** [comment]
I'm sure there's a short time between a voice over that yells about an incoming energy beam and the actual destruction of the base.

**Comment by GraveyBoi** [comment]
actually no, it happens immediately

**Comment by GraveyBoi** [comment]
you get the tech to the generator and then, poof, goodbye base

**Comment by JJ173** [comment]
Either solution proposed doesn't make sense at least from a lore perspective for this part of the mission. 

The EDF are limited in number for this part of the campaign and their numbers are only getting smaller. It also wouldn't take 30 or 60 seconds for the beam to hit the base when fired. By the time they detect it, it's already too late.

**Comment by Feared1** [comment]
I can't remember for sure, but I believe there was a countdown of some kind?

The alternative solution I proposed was to give me reinforcements to end the mission with. In fact, there is a voiceover in there saying that there are reinforcements coming in (I believe) but they just never showed up. These reinforcements should be sufficient enough to end the mission, otherwise it's a possible dead end (unless you WAIT for whatever vehicle you are piloting to regenerate enough ammo to kill the Procreator AND Xenomater).

**Comment by JJ173** [comment]
I have confirmed that the voice line does occur and there's a 30 second timer before the energy beam strikes your base.

Closed for now.
