### ISSUE TITLE
Inconsistent Recycler names

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#58]
In the back of my mind, mission 3-5 may have referred to the Recycler as "VENGEANCE," not PEACEMAKER, the PEACEMAKER should be the ORIGINAL, the VENGEANCE is the second one.

The Peacemaker is also used for your Recycler name in the Mission 6 debriefing, but it should be the VENGEANCE.

**Comment by JJ173** [comment]
Done a sweep as part of #170 to fix.
