### ISSUE TITLE
ODF: Inheritance support

### ISSUE THREAD

**Issue by BlackDragonN001** [BlackDragonN001/FERemastered#6]
Modifying ODFs that use the same MSH / item to inherit off the parent.

Another 1.3 feature that wasn't possible in 1.2. Implementing it early will save time later.

**Comment by JJ173** [comment]
I'm half way through this with the Cerberi, so I may as well finish the task.

**Comment by JJ173** [comment]
Added to the BZCC branch, ready for review.

**Comment by JJ173** [comment]
Closing this as part of the clean-up. This update was implmented.
