### ISSUE TITLE
Mission 6: Long wait time for Recycler

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#66]
Extremely long wait time for the recycler to get to the portal, but maybe intentional for less-experienced players who need more time to take out the spikes?

Maybe add some attackers?

**Comment by JJ173** [comment]
If we implement a difficulty option, this could be a good thing to consider.

**Comment by GraveyBoi** [comment]
As much as we would have like to we no longer have the support to make this happen.
