### ISSUE TITLE
Mission 7: Radio Interference

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#68]
The random radio interference sounds should be briefly "painting" a far away structure every time a sound is made, but it does not (or it is difficult to see because it happens too fast OR inconsistently) 

When "captian eisensetin" comes to check it out, he stops several hundred meters away from the structure (out of sight range through the fog), I didn't know what he was talking about at first.

**Comment by JJ173** [comment]
I am not sure this is an issue. IIRC this has always been the same as 1.2. Sometimes it will randomly highlight based on a random duration which I believe is intentional. 

Unless @BlackDragonN001 has any input, I don't see why this should be changed.
