### ISSUE TITLE
Mission 9: hawk sound

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#77]
There was a hawk sound on this map...somewhere southwest of the missile turret (there are no hawks on Miasma).

**Comment by JJ173** [comment]
Likely a small soundcube that's been placed by accident. Will have a look at removing.

**Comment by Malifious** [comment]
Adding on to this, on Hidden Threats, by the scrap pool in that valley to the SW of your base is another sound cube. This one sounds like a jaguar or something. Some kind of big cat.
