### ISSUE TITLE
AIP Provides

### ISSUE THREAD

**Issue by BlackDragonN001** [BlackDragonN001/FERemastered#8]
Ensure the CORE race assets used in IA/MP for Hadean and Cerberi have the proper provide Names needed for AIPs.

**Comment by JJ173** [comment]
I've also started doing this for the Cerberi, so I'll do the same for the Hadeans.

**Comment by JJ173** [comment]
Commit ready for reviewing to close this task: https://github.com/BlackDragonN001/FERemastered/commit/cebd6b286e9767bb9af534b953d2d205bb419786

**Comment by JJ173** [comment]
Closing - task is complete.
