### ISSUE TITLE
Mission 10: Extractors don't take damage from earthquakes

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#81]
I could easily build an entire base and survive indefinitely (I could do this anyway, but the scrap pools taking damage would make this more difficult)

**Comment by JJ173** [comment]
The damage for each building is controlled by the mission. We would probably need to update this function so instead it damages all player buildings instead of some hardcoded ones.

**Comment by JJ173** [comment]
Fixed.
