### ISSUE TITLE
Mission 11: portal death trap

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#83]
Tracked units going through the portal to the biometal pool island fall into the water and die after going through the portal - extend terrain a bit

**Comment by GraveyBoi** [comment]
![DropOffOrientation](https://user-images.githubusercontent.com/53205387/82085703-670a4b00-96bb-11ea-8f8b-bc6310d1c413.jpg)

**Comment by GraveyBoi** [comment]
They skid down the side and die. I'll extend the terrain  a bit and make a small lip so they don't fly past.
