### ISSUE TITLE
Gun towers need infinite ammo

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#89]
See VSR gun towers - they have infinite ammo (instead of finite ammo that regenerates really fast) so healers stop trying to heal in between shots).

**Comment by bornlibra23** [comment]
Hopefully the healers will still heal damage. I hope there is no side effect. Doesnt seem to be from the changes.

**Comment by jack775544** [comment]
Yes they will. My changes only made it so the weapon that gun towers use consume 0 ammo.
