### ISSUE TITLE
Strange tank AI problems

### ISSUE THREAD

**Issue by Feared1** [BlackDragonN001/FERemastered#90]
When giving multiple tanks go-to's, they will often just spin in place for a few seconds before actually doing what you asked.

**Comment by GraveyBoi** [comment]
I've noticed this as well, generally happens in large groups of them.

**Comment by JJ173** [comment]
This is a base game issue. If you test this in Stock, you will get the same problem. This has been a problem since Rebellion published an "AI Update" in their penultimate patch.
