### ISSUE TITLE
Game: Sometimes objective text box in the mission briefings is too small

### ISSUE THREAD

**Issue by bornlibra23** [BlackDragonN001/FERemastered#95]
Sometimes objective text box in the mission briefings is too small & requires scrolling using the wheel & it doesnt have a scroll bar so the message appears to be cut before the end. Also the actual graphical design box is large enough so I guess the text box can be resized.

**Comment by bornlibra23** [comment]
What happened? A base game issue?

**Comment by bornlibra23** [comment]
I am talking about the screen which exists before the mission starts not the white worded on in the game during gameplay.

**Comment by Feared1** [comment]
The objectives need to be shortened.

**Comment by GraveyBoi** [comment]
Locking this, please use the open ticket

**Comment by JJ173** [comment]
This is a duplicate of: #36 

Please try to check if your issue has been raised before raising another.
